name: gromacs-tutorials-workshop
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib
  - nglview
  - mdtraj
  - notebook
  - numpy
  - requests
  - pandas
  - seaborn
  - compilers
  - openmpi
  - cmake
